### ISSUE TITLE
Fullfil ip location variable onle

### ISSUE THREAD

**Issue by evertramos** [midnite81/geolocation#5]
Hello @midnite81 

it´s not an issue... but I think this should be a nice package for Laravel.

I have implemented as a access logger with an Event I could share some code if you would.

Just a small question, what is this precision variable?

I had to use `getCity` in order to fullfill the `$geo` I believe it would be nice to have some `$geo->get()` with some default value for `$precision`.

What do you think?

**Comment by midnite81** [comment]
The precision variable defines what level of precision you want. 

Country only gets you the country, city gets you the city and country. See http://ipinfodb.com/ip_location_api.php for more detail (under the API list section)

I've updated $geo->get() to have a default precision of 'city'. I have tagged the release as [v1.0.2](../tree/v1.0.2). 

Yeah always good to see code if you want to share.

**Comment by evertramos** [comment]
I see! Nice!!

Well I never developed a Laravel Package, here is the code I implemented:

Migration
```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAccessLogTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('access_log', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned()->index();
            $table->ipAddress('ipAddress')->nullable();
            $table->string('countryCode', 2)->nullable();
            $table->string('countryName')->nullable();
            $table->string('regionName')->nullable();
            $table->string('cityName')->nullable();
            $table->string('zipCode')->nullable();
            $table->decimal('latitude', 10, 7)->nullable();
            $table->decimal('longitude', 10, 7)->nullable();
            $table->timeTz('timeZone')->nullable();
            $table->string('addressString')->nullable();
            $table->timestamps();
        });

        Schema::table('access_log', function (Blueprint $table) {
            $table->foreign('user_id')->references('id')->on('users')->onDelete('restrict');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('access_log', function (Blueprint $table) {
            $table->dropForeign('access_log_user_id_foreign');
        });

        Schema::dropIfExists('access_log');
    }
}
```


Event Listener
```php
<?php

namespace App\Listeners;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Midnite81\GeoLocation\Contracts\Services\GeoLocation;

class UserRegisterAccess
{
    // Users Request
    protected $request;

    // GeoLocation
    protected $geo;

    /**
     * Create the event listener.
     *
     * @return void
     */
    public function __construct(Request $request, GeoLocation $geo)
    {
        $this->request = $request;
        $this->geo = $geo;
    }

    /**
     * Handle user login events.
     */
    public function onUserLogin($event)
    {
        // Get Users' Location Data
        $ipLocation = $this->geo->getCity($this->request->header('x-real-ip'));

        // Salva dados do acesso no banco de dados
        Auth::user()->acessos()->create($ipLocation->toArray());
    }

    /**
     * Register the listeners for the subscriber.
     *
     * @param  Illuminate\Events\Dispatcher  $events
     */
    public function subscribe($events)
    {
        $events->listen(
            'Illuminate\Auth\Events\Login',
            'App\Listeners\UserRegisterAccess@onUserLogin'
        );
    }
}
```

And it must add the following line to the `EventServiceProvider.php` file:

```php
    /**
     * The subscriber classes to register.
     *
     * @var array
     */
    protected $subscribe = [
        'App\Listeners\UserRegisterAccess',
    ];
```

That's it!

I follow the Laravel Standards for subscribe Event as in the docs.

The new package if not your, will be 100% dependable of this geolocation repo! =)

**Comment by evertramos** [comment]
I mean, as you are the idealist of the package there is the code! If you get it into a package will be nice too!

I study a little it´s not that hard to publish the migration, not sure how do add the event listener.

Also I will get some views done in a few and can send it to you too.

**Comment by evertramos** [comment]
Just one more comment I use nginx reason why to get the ip address from header the proxy or your nginx config must have the following option: 

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/master/conf.d/realip.conf

And my current environment run under this web proxy:

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
