### ISSUE TITLE
Composer 2 autoload deprecation notice

### ISSUE THREAD

**Issue by sgatz** [midnite81/geolocation#7]
Deprecation Notice: Class Midnite81\GeoLocation\Facades\Geolocation located in ./vendor/midnite81/geolocation/src/Facades/GeoLocation.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

**Comment by midnite81** [comment]
Thanks for reporting @sgatz. I will take a look today.

**Comment by midnite81** [comment]
@sgatz This has been fixed - please update the midnite81/geolocation dependency in your composer json to be v2.0.0 or higher. Thanks again for reporting it.

**Comment by sgatz** [comment]
Thanks so much, I've updated it!
