### ISSUE TITLE
Undefined property: stdClass::$statusCode

### ISSUE THREAD

**Issue by merobal** [midnite81/geolocation#9]
It seems the API response has been updated, I get:

```
{#402 ▼
  +"status": "OK"
  +"message": ""
  +"ipAddress": "::1"
  +"countryCode": "-"
  +"countryName": "-"
  +"regionName": "-"
  +"cityName": "-"
  +"zipCode": "-"
  +"latitude": "0"
  +"longitude": "0"
  +"timeZone": "-"
}
```

So it breaks at:
```
        $this->statusCode = ! empty($resp = $response->statusCode) ? $resp : '';
        $this->statusMessage = ! empty($resp = $response->statusMessage) ? $resp : '';
```

with error message `Undefined property: stdClass::$statusCode`

**Comment by midnite81** [comment]
Thanks for reporting the bug, @merobal. I will take a look shortly.

**Comment by midnite81** [comment]
Apologies for taking so long to get around to this @merobal. I cannot recreate the issue you're having. Are you still having these issues?
